{% set name = "geodata-harvester" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geodata-harvester-{{ version }}.tar.gz
  sha256: b87002de80687f74d97f0b357de95d7aca2d4b3254e9ff3557941c2b7f66ce9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - rasterio
    - termcolor
    - xarray
    - matplotlib-base
    - alive-progress >=3.0.1
    - owslib ==0.27.2
    - netcdf4
    - rioxarray
    - pyyaml
    - pandas
    - geopandas
    - pyproj
    - numba
    - shapely
    - fiona >=1.8.21
    - ipywidgets >=7.6.5
    - ipython
    - eeharvest
    - schema
    - requests ==2.28.1

test:
  imports:
    - geodata_harvester
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Sydney-Informatics-Hub/geodata-harvester
  summary: An automation tool for harvesting and processing geodata from the web
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sebhaan
